[package]
name = "rAstCoder"
version = "0.1.0"
authors = ["Acasune <tttt4aaaa@gmail.com>"]
edition = "2018"


[dependencies]
reqwest ={version="0.11.10",features=["blocking"]}
scraper = "0.13"
selectors ="0.23.0"
regex = "1"
futures = "0.3"
run_script="0.9"
tokio="1.18.1"
anyhow = "1.0.57"
